version: '3.7'

services:
 postgresql:
  image: postgres
  ports:
   - '5432:5432'
  volumes:
   - ./data:/var/lib/postgres
  environment:
   POSTGRES_DATABASE: app
   POSTGRES_USER: app
   POSTGRES_PASSWORD: 12345