version: '3.7'

services:
 postgresql:
  image: postgres
  ports:
   - '3306:3306'
  volumes:
   - ./data:/var/lib/postgres
  environment:
   postgres_database: app
   postgres_user: app
   postgres_password: 12345