version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '3306:3306'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local