version: '3.7'

services:
 postgresql:
  image: postgres
  ports:
   - '9999:5432'
  volumes:
   - ./data:/var/lib/postgres
  environment:
   postgresql_database: app
   postgresql_user: app
   postgresql_password: 12345