version: '3.7'

services:
  postgresql:
    image: postgres
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
environment:
	mysql_database: app
	mysql_user: app
	mysql_password: 12345
	# postgres_database: app
	# postgres_user: app
	# postgres_password: 12345